export type Stats = {
  seconds: number,
  fgMade: number,
  fgAttempted: number,
  fg3Made: number,
  fg3Attempted: number,
  ftMade: number,
  ftAttempted: number,
  offRebounds: number,
  defRebounds: number,
  assists: number,
  steals: number,
  blocks: number,
  turnovers: number,
}
